# Generated by Django 4.0.4 on 2022-06-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.subcategory'),
        ),
    ]
