# Generated by Django 4.0.4 on 2022-06-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rawproduct_category_rawproduct_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawproduct',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
