# Generated by Django 4.0.4 on 2022-06-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rawproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='imageUrl',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
