# Generated by Django 4.0.4 on 2022-06-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawproduct',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.subcategory'),
        ),
    ]
