# Generated by Django 4.0.4 on 2022-06-22 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rawproduct_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='mycategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
