# Generated by Django 4.0.4 on 2022-06-22 10:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rawproduct_mycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='api_product_vector__2551ac_gin'),
        ),
    ]
