# Generated by Django 4.0.4 on 2022-06-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_vector_column_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
